name: CI - Build wxPython

on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-14

    env:
      branch: ${{ github.ref }}
      commiturl: ${{ github.event.head_commit.url }}${{ github.event.release.html_url }}
      commitdate: ${{ github.event.head_commit.timestamp }}${{ github.event.release.published_at }}

      ANALYTICS_KEY: ${{ secrets.ANALYTICS_KEY }}
      ANALYTICS_SITE: ${{ secrets.ANALYTICS_SITE }}

      ORG_MAC_DEVELOPER_ID_APPLICATION_IDENTITY:
